# Generated by Django 4.1.7 on 2023-04-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_product_orderplaced_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
    ]
